name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purs-tidy: "latest"

      - name: Install esbuild
        run: npm install --global esbuild@0.14.38

      - name: Build source
        run: npm run build

      - name: Build examples
        run: npm run examples

      - name: Verify formatting
        run: purs-tidy check src example
